name: Android

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          graalvm: '21.3.0-dev-20210713_1945'

      - name: Install libraries
        run: sudo apt update; sudo apt install -y maven libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev

      # https://developer.android.com/studio/publish/app-signing
      - name: Setup Android Keystore
        id: android_keystore_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'my.keystore'
          encodedString: ${{ secrets.GLUON_ANDROID_KEYSTORE_BASE64 }}
          
      - name: Gluon Build
        run: mvn -Pandroid gluonfx:build gluonfx:package
        env:
          GLUON_ANDROID_KEYSTOREPATH: ${{ steps.android_keystore_file.outputs.filePath }}
          GLUON_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.GLUON_ANDROID_KEYSTORE_PASSWORD }}
          GLUON_ANDROID_KEYALIAS: ${{ secrets.GLUON_ANDROID_KEYALIAS }}
          GLUON_ANDROID_KEYALIAS_PASSWORD: ${{ secrets.GLUON_ANDROID_KEYALIAS_PASSWORD }}

      - name: Make staging directory
        run: mkdir staging

      - name: Copy native clients to staging
        run: cp -r target/gluonfx/aarch64-android/gvm/semux-core.apk staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging


      # - name: Upload to Google Play
      #   uses: r0adkll/upload-google-play@v1
      #   with:
      #     serviceAccountJsonPlainText: ${{ secrets.GLUON_ANDROID_SERVICE_ACCOUNT_JSON }}
      #     packageName: io.zzv.view
      #     releaseFiles: target/gluonfx/aarch64-android/gvm/semux-core.apk
      #     track: alpha
