name: Linux-Docker

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install libraries
        run: sudo apt update; sudo apt install -y maven libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev

      - name: Enable SWRendering
        run: cp src/linux/pom.xml pom.xml

      - name: Gluon Build
        run: mvn -Pdesktop gluonfx:build gluonfx:package

      # - name: Copy native app to zzv-apt-package
      #   run: |
      #     mkdir -p src/linux/zzv_1.0.1_amd64/usr/local/bin/;
      #     cp target/gluonfx/x86_64-linux/semux-core src/linux/zzv_1.0.1_amd64/usr/local/bin/semux-core

      # - name: Build apt-repository
      #   run: cd src/linux && bash gpg.sh && bash package.sh
      #   env: 
      #     GPG_PASS: ${{ secrets.GPG_PASS }}

      - name: Make staging directory
        run: mkdir staging

      - name: Copy apt repo to staging
        run: cp -r target/gluonfx/x86_64-linux/semux-core staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging