name: MacOS

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: [self-hosted, macOS, X64]
    steps:
      - uses: actions/checkout@v2

      - uses: zzvio/setup-graalvm@5.3
        with:
          graalvm: '21.3.0-dev-20210713_1945'
          java: java11

      - name: Gluon Build
        run: mvn clean
    
      - name: Gluon Build
        run: mvn gluonfx:build gluon:package

      # - name: Import MACOS_APP_CERT
      #   uses: Apple-Actions/import-codesign-certs@v1
      #   with:
      #     keychain: MACOS_APP_CERT_KEYCHAIN
      #     p12-file-base64: ${{ secrets.GLUON_MACOS_APP_CERT_FILE_BASE64 }}
      #     p12-password: ${{ secrets.GLUON_MACOS_CERTIFICATES_PASSWORD }}

      # - name: Codesign
      #   env:
      #     APP_CERT_NAME: ${{ secrets.GLUON_MACOS_APP_CERT_NAME }}
      #   run: bash -x src/osx/codesign.sh

      # - name: Import MACOS_INSTALLER_CERT
      #   uses: Apple-Actions/import-codesign-certs@v1
      #   with:
      #     keychain: MACOS_INSTALLER_CERT_KEYCHAIN
      #     p12-file-base64: ${{ secrets.GLUON_MACOS_INSTALLER_CERT_FILE_BASE64 }}
      #     p12-password: ${{ secrets.GLUON_MACOS_CERTIFICATES_PASSWORD }}

      # - name: Build zzv.pkg
      #   env: 
      #     PRIV_KEY: ${{ secrets.GLUON_IOS_APPSTORE_PRIVATE_KEY }}
      #     INSTALLER_CERT_NAME: ${{ secrets.GLUON_MACOS_INSTALLER_CERT_NAME }}
      #   run: bash -x src/osx/osx.sh

      - name: Make staging directory
        run: mkdir staging

      - name: Copy native clients to staging
        run: cp -r target/gluonfx/x86_64-darwin/semux-core staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging

      # - name: Upload to Mac store
      #   env: 
      #     APPSTORE_KEY_ID: ${{ secrets.GLUON_IOS_APPSTORE_KEY_ID }}
      #     APPSTORE_ISSUER_ID: ${{ secrets.GLUON_IOS_APPSTORE_ISSUER_ID }}
      #   run: bash -x src/osx/upload.sh
