name: MacOS

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: [self-hosted, macOS, X64]
    steps:
      - uses: actions/checkout@v2

      - uses: zzvio/setup-graalvm@5.3
        with:
          graalvm: '21.3.0-dev-20210729_2115'
          java: java11

      - name: Mvn clean
        run: mvn dependency:purge-local-repository -Dverbose=true
    
      - name: Gluon Compile
        run: mvn gluonfx:build gluonfx:package 

      - name: Import MACOS_APP_CERT
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          keychain: MACOS_APP_CERT_KEYCHAIN
          p12-file-base64: ${{ secrets.GLUON_MACOS_APP_CERT_FILE_BASE64 }}
          p12-password: ${{ secrets.GLUON_MACOS_CERTIFICATES_PASSWORD }}

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   env:
      #     APP_CERT_NAME: ${{ secrets.GLUON_MACOS_APP_CERT_NAME }}
      #     PRIV_KEY: ${{ secrets.GLUON_IOS_APPSTORE_PRIVATE_KEY }}
      #     INSTALLER_CERT_NAME: ${{ secrets.GLUON_MACOS_INSTALLER_CERT_NAME }}
      #     APPSTORE_KEY_ID: ${{ secrets.GLUON_IOS_APPSTORE_KEY_ID }}
      #     APPSTORE_ISSUER_ID: ${{ secrets.GLUON_IOS_APPSTORE_ISSUER_ID }}

      - name: Codesign
        env:
          APP_CERT_NAME: ${{ secrets.GLUON_MACOS_APP_CERT_NAME }}
        run: bash -x src/osx/codesign.sh

      - name: Import MACOS_INSTALLER_CERT
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          keychain: MACOS_INSTALLER_CERT_KEYCHAIN
          p12-file-base64: ${{ secrets.GLUON_MACOS_INSTALLER_CERT_FILE_BASE64 }}
          p12-password: ${{ secrets.GLUON_MACOS_CERTIFICATES_PASSWORD }}

      - name: Build zzv.pkg
        env: 
          PRIV_KEY: ${{ secrets.GLUON_IOS_APPSTORE_PRIVATE_KEY }}
          INSTALLER_CERT_NAME: ${{ secrets.GLUON_MACOS_INSTALLER_CERT_NAME }}
        run: bash -x src/osx/osx.sh

      - name: Make staging directory
        run: mkdir staging

      - name: Copy native clients to staging
        run: cp -r target/gluonfx/x86_64-darwin/semux-core staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging

      - name: Upload to Mac store
        env: 
          APPSTORE_KEY_ID: ${{ secrets.GLUON_IOS_APPSTORE_KEY_ID }}
          APPSTORE_ISSUER_ID: ${{ secrets.GLUON_IOS_APPSTORE_ISSUER_ID }}
        run: bash -x src/osx/upload.sh

